server:
  port: 8082

spring:
  application:
    name: receiver-server
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

signature:
  pairs:
    - id: 20231123
      path: 20231123/publicKey.pem
    - id: 20231205
      path: 20231205/publicKey.pem

logging:
  level:
    root: info
