server:
  port: 8082

spring:
  application:
    name: spring-verify-server
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

encrypt:
  name: publicKey.pem

logging:
  level:
    root: debug
